### ISSUE TITLE
add logging for converted files

### ISSUE THREAD

**Issue by wrbrant** [idaholab/cape2stix#18]
- [x] when converting in convert.py, failed conversions need the file path logged.
- [x] catch and log failures with [target][category]
- [x] catch and log attack pattern/extension fails

**Comment by mcutshaw** [comment]
Still need the lat one.

**Comment by wrbrant** [comment]
attack-pattern fails are logged as of 3431409b663c0d9a4c580d29d35e6f734278fd78 
Requires further investigation.
